### PR TITLE
stat is now autogenerated correctly

### PR DESCRIPTION
**Pull request by sajattack**

### CODE REVIEW

**Comment by sajattack** [comment]
CI is failing because the cbindgen link isn't updated in this PR, but it will be once merged.

**Comment by jackpot51** [comment]
@sajattack you can update the submodule in your PR:

```
cd cbindgen
git checkout master
git pull
cd ..
git commit -m "Update cbindgen" cbindgen
```

**Comment by sajattack** [comment]
@jackpot51 My bad, thought it was updated already.

**Comment by jackpot51** [comment]
Can you update the lockfile with cargo update?

**Pull request merged**
