### PR TITLE
implement pipe and read

### PR DESCRIPTION
**Pull request by sajattack**
still needs some tests and the redox implementation of pipe has some crusty conversion

### CODE REVIEW

**Comment by jackpot51** [comment]
You really shouldn't need allocation to convert a [c_int; 2] to [usize; 2]

**Comment by sajattack** [comment]
I was told it needs allocation because the usize could be a different size than the c_int

**Comment by jackpot51** [comment]
Who told you that?

**Comment by jackpot51** [comment]
I also merged this. Please look at the patch I made: https://github.com/redox-os/relibc/commit/cfbe27490f30a127a55c4bb165fea53a86338b77

There is no reason to allocate - be careful not to jump to allocation to try to solve problems in a C library.

**Comment by sajattack** [comment]
mburbeck on #rust-beginners

**Pull request merged**
