### PR TITLE
add bindgen post-processing script, use it for a bunch of headers

### PR DESCRIPTION
**Pull request by sajattack**

### CODE REVIEW

**Comment by sajattack** [comment]
I was gonna to stdio.h but I can't figure out what a f_pos_t is supposed to be.

**Comment by jackpot51** [comment]
I do not like that this undid my work with unistd and naming the arguments.

**Comment by Restioson** [comment]
How so?

**Comment by jackpot51** [comment]
All the argument names are now arg1, arg2, etc. instead of path, fildes, etc.

**Comment by Restioson** [comment]
Ah I see; I thought you were referring to regression in the current code.

**Comment by jackpot51** [comment]
I was, I had manually created half of the unistd functions using the correct argument names

**Comment by Restioson** [comment]
Ah, I see now browsing the PR's tree.

**Comment by sajattack** [comment]
@jackpot51

**Pull request merged**
